server:
  port: 8080
spring:
  application:
    name: "AuthService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    usuarios: "/api/v1/usuarios"
    usuariosPorId: "/api/v1/usuarios/{id}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_usuarios"
    schema: "public"
    username: "postgres"
    password: "12345678"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

jwt:
  secret: 9327c14da34fb6f1400f4f457a9108a88a227ae9e5865840756a6f211b31c3df8183dd2b914c92777f7ad24d59893f05a575bbe32d3e1ad626a726327b3b4d26
  expiration: 86400000
